### ISSUE TITLE
URL generated with query parameters are not working

### ISSUE THREAD

**Issue by blues-man** [redhat-scholars/course-ui#6]
Hello,

when using placeholder as `%CLUSTER_SUBDOMAIN%` inside a `link`, they are not interpreted good by Antora and the link is broken, example:

https://redhat-scholars.github.io/openshift-starter-guides/rhs-openshift-starter-guides/common-explore.html?CLUSTER_SUBDOMAIN=apps.my-cluster.tld&PROJECT_NAMESPACE=workshop&USERNAME=foo&PASSWORD=foo

It is rendered as:
```
<a href="http://console-openshift-console.%CLUSTER_SUBDOMAIN%/k8s/cluster/projects">Web Console</a>
```

**Comment by kameshsampath** [comment]
@blues-man  I am not replacing all the anchor links, as that will break the external links or other places where we dont need t send the parameters. If you want your link to have the query string appended then write your link like:
```asciidoc
https://console.openshift.com[OpenShift Console,role='query-params-link']
```
That gets rendered with query parameter appended.  Can you usecase fit this?

**Comment by kameshsampath** [comment]
based on the discussion overt the meeting, I am closing this.
